project_id = "lsjzutqmwjdkhasndxbf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lsjzutqmwjdkhasndxbf.supabase.co"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.sponsorship-forecast]
verify_jwt = false

[functions.sponsorship-pricing]
verify_jwt = false

[functions.revenue-analysis]
verify_jwt = false

[functions.advanced-segmentation]
verify_jwt = false

[functions.export-report]
verify_jwt = false

[functions.clustering]
verify_jwt = false

[functions.generate-segment-insights]
verify_jwt = false

[functions.orchestrator]
verify_jwt = false