// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsjzutqmwjdkhasndxbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzanp1dHFtd2pka2hhc25keGJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NDQzMDMsImV4cCI6MjA3NDQyMDMwM30.klJ4ZbvZGpI6hPydjuRJnwUO-H3VeOIfHouMDkZ2npQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});